# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Java Maven app and push to Google Container Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maven:
    runs-on: ubuntu-latest

    steps:
    - name: Clone source code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
  gcr:
    needs: maven
    runs-on: ubuntu-latest
    steps:
      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: __json_key
          password: ${{secrets.GCP_SA_GCR}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          tags: gcr.io/${{secrets.GCP_PROJECT_ID}}/filmsfetcher

